### ISSUE TITLE
Awesome repo!

### ISSUE THREAD

**Issue by kevinzakka** [ccnmaastricht/angorapy#20]
Just stumbled on this repo, really impressive engineering effort! Its particularly funny to me as well because I've been working on a [dexterous hand benchmark](https://github.com/kevinzakka/dexterity) in parallel but I chose the `dm_control`/`dm_env` route. Very happy to see different efforts on this end :) 

Out of curiosity, was wondering how successful you've been training policies on the various envs, for e.g. `reaching`? Have you tried harder variants where you completely randomize the joint angles and try to reach the corresponding poses in space? (this is hard because the hand is under-actuated) 

Cheers!

**Comment by weidler** [comment]
Nice to hear that you are working on dexterity! While with AngoraPy, we are focusing on training biologically plausible models and not on building environments, I was previously considering detaching our predefined tasks in some separate repo. Might instead have a look at your package and see if we can build around it when building the environments. Thanks for pointing us towards it! Did you by any chance consider using muscle actuators instead of steering joints directly?

For `reaching` we have been successful with tasks like finger opposition sequences, but indeed starting at random initial conditions complicates things. `manipulation` also works very well but requires substantially more data per PPO cycle. The same should apply to harder variants of `reaching`. I will keep you posted if we go in that direction again.

**Comment by kevinzakka** [comment]
Hi @weidler, apologies for the delayed reply.

I'd love for y'all to build on the repo to define your tasks, and I'd love to support you if the repo does not have things you require.

> Did you by any chance consider using muscle actuators instead of steering joints directly?

Currently, the shadow hand in the repo is position-controlled (which is not how it is implemented on real hardware), but I'd love to create a variant that is muscle actuated and also one that is cable-driven as on the real hardware. Definitely on my todos!

> For reaching we have been successful with tasks like finger opposition sequences

Out of curiosity, what do you mean by "finger opposition sequences"?
